### ISSUE TITLE
Copilot inline suggestions color

### ISSUE THREAD

**Issue by apirrone** [kcamcam/vscode_dark_modern.zed#11]
Hello, 

I was very glad to see this extension theme for zed, as this is the theme I used in vscode, so thanks a lot !

My only complaint is that copilot's inline suggestions are displayed in plain white, which is a little distracting to me. For example : 

zed : 
![Capture d’écran du 2024-08-02 22-31-53](https://github.com/user-attachments/assets/5e8a2e80-285f-404a-a9e8-3469dd9c574e)

vscode : 
![Capture d’écran du 2024-08-02 22-33-51](https://github.com/user-attachments/assets/f5cf2b1e-b1af-4697-964d-20617c7b99c2)

Can I tweak that somehow ? 

Thanks !

**Comment by kcamcam** [comment]
Thanks for sharing your complaint @apirrone.

There is already a pull request open to address this #5.

**Comment by apirrone** [comment]
The new version fixed this, wonderful !
