### ISSUE TITLE
Colors a little off / distracting

### ISSUE THREAD

**Issue by MatthewScholefield** [kcamcam/vscode_dark_modern.zed#3]
I'm not sure if it's just something different with theming with recent versions, but to me it seems a lot of the background colors, especially for subtle things like hover or for the current line are a little too bright and distracting:

![image](https://github.com/user-attachments/assets/739c32f1-d0d0-4d63-8b2d-34d3448adc30)

I've gone ahead and added some theme overrides that IMO make things a lot nicer:

![image](https://github.com/user-attachments/assets/8db62420-8d87-42f3-b9a3-e48cdbae4815)

In case anyone wants to use the same overrides, here they are:

```json
"experimental.theme_overrides": {
    "editor.active_line.background": "#cccccc01",
    "predictive": "#515151",
    "editor.document_highlight.read_background": "#ffffff04",
    "element.hover": "#ffffff01",
    "element.active": "#ffffff04",
    "ghost_element.hover": "#ffffff01",
    "ghost_element.selected": "#333333",
    "hint": "#ffffff08",
    "warning.background": "#674500",
    "editor.indent_guide": "#ffffff0a",
    "editor.indent_guide_active": "#ffffff26"
}
```

Just creating this issue in case it is helpful for anyone else. I may consider creating a forked theme if I get some time in the future.

**Comment by kcamcam** [comment]
@MatthewScholefield thanks for providing screen shots along with the issue and for leaving a workaround for anyone else that finds this issue. This was addressed in #1 and was just merged int the Zed extensions repo https://github.com/zed-industries/extensions/pull/1032. It should be available in the Zed extensions store now.

Please feel free to open a pull request if you find any other styling is missing.
