### ISSUE TITLE
Track manual changes with CUSTOMIZATIONS.md

### ISSUE THREAD

**Issue by 2zqa** [kcamcam/vscode_dark_modern.zed#9]
Like described in my comment here (https://github.com/kcamcam/vscode_dark_modern.zed/issues/2#issuecomment-2243752200), I have tried my own hand at creating a repository which has both Modern Dark and Modern Light themes included. I adopted the idea of tracking changes in [CUSTOMIZATIONS.md](https://github.com/2zqa/vscode_modern_themes.zed/blob/main/CUSTOMIZATIONS.md), because this would allow us to track which values are generated by the importer and which ones are manually created.

Pros:
* It allows us to easily see which values we should overwrite and which we maybe want to keep if the theme_importer program behavior changes (e.g. it generates different color values for certain fields).

Cons:
* It adds additional work, especially when changing many values manually, maybe deterring people from contributing
* This is extra effort to try to account for theoretical changes to theme_importer that may or may not even occur
* Requires close attention during reviewing, although theoretically this process could be automated with a script (I tried this, didn't end up finishing it)

So if you're not sold on the idea, feel free to close this issue.

**Comment by kcamcam** [comment]
Thanks for the issue @2zqa.

I agree with the pros and cons. Ultimately I think that the extra cost in maintainability outweighs the mentioned pros.

Let's leave the issue open to see if anyone else has an opinion or other ideas.

**Comment by 2zqa** [comment]
It's been two weeks, I'll go ahead and close this. Looking back at this issue, it's probably not worth it. Plus, git blame can be used in dire situations.
